# Generated by Django 6.0.3 on 2026-03-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название системы')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('level_count', models.PositiveSmallIntegerField(verbose_name='Количество уровней')),
                ('energy_unit', models.CharField(choices=[('Hz', 'Hz'), ('kHz', 'kHz'), ('MHz', 'MHz')], default='MHz', max_length=8, verbose_name='Единицы энергии')),
                ('level_spacing', models.FloatField(default=1.0, verbose_name='Типичный энергетический зазор')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация системы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Квантовая система',
                'verbose_name_plural': 'Квантовые системы',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_state_mode', models.CharField(choices=[('state_vector', 'Вектор состояния'), ('density_matrix', 'Матрица плотности')], max_length=24, verbose_name='Режим начального состояния')),
                ('initial_state_code', models.TextField(verbose_name='Код QuTiP для начального состояния')),
                ('evolution_time', models.FloatField(verbose_name='Длительность эволюции')),
                ('time_unit', models.CharField(choices=[('s', 's'), ('ms', 'ms'), ('us', 'us'), ('ns', 'ns')], default='us', max_length=8, verbose_name='Единицы времени')),
                ('time_steps', models.PositiveIntegerField(default=400, verbose_name='Количество временных шагов')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='Результаты симуляции')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='Служебные данные')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='simulator.quantumsystem', verbose_name='Квантовая система')),
            ],
            options={
                'verbose_name': 'Запуск симуляции',
                'verbose_name_plural': 'Запуски симуляции',
                'ordering': ['-created_at'],
            },
        ),
    ]
